ChickenChess/ChickenChess/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from .views import *
from .initdbs import *
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
import json

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$|^/$|^home/$', home, name='home'),
    path('partita', match, name='partita'),
    path('players/', include('players.urls')),
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("success/", success, name='success'),
    path('game/', include('game.urls'), name='game'),
    path('getmoves/',getmoves),
    path('makemove/',makemove),
    

    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

#erase_dbs()
#start_dbs()



ChickenChess/game/urls.py
from django.urls import path
from .views import *

app_name = 'game'

urlpatterns = [
 path("<str:inviting>/<str:color>/", game ,name="game"),
 path('lobby/', LobbyView.as_view() , name='lobby'),
 path('creategame/', creategame, name='creategame'),



]

ChickenChess/game/models.py
from typing_extensions import Required
from django.db import models
from players.models import profile


# Create your models here.
class Pending_Game(models.Model):
    WHITE = 'white'
    BLACK = 'black'
    COLOR_PLAYER = [(WHITE,'white'),(BLACK,'black')]

    inviting = models.CharField(default= '',max_length=30)
    invited = models.CharField(default= '',max_length=30) 
    color_inviting = models.CharField(choices=COLOR_PLAYER, max_length=5)
    time = models.IntegerField()
    increment = models.IntegerField()

ChickenChess/game/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from .models import Pending_Game,profile
from django.db import models

class createGameForm(forms.ModelForm):
    description = 'create a new game to publish in the lobby'

    def __init__(self, *args, **kwargs):
        
        self.userid = kwargs.pop('profileid', None)
        self.profileid = profile.objects.get(id = self.userid)
        
        
        super(createGameForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get('time')<0 or cleaned_data.get('increment') < 0:
            raise forms.ValidationError('Time must be positive')
        if cleaned_data.get('inviting') != self.userid:
            raise forms.ValidationError('you must be the Inviting player')

        

    class Meta:
        model = Pending_Game
        fields = ['inviting','color_inviting','time','increment']
        widgets = {'color_iniviting': forms.RadioSelect , 'time': forms.NumberInput,'increment': forms.NumberInput}

ChickenChess/game/views.py
from django.forms import ValidationError
from django.http import Http404
from django.shortcuts import render,redirect
from django.views.generic import ListView, CreateView
from game.models import Pending_Game
from players.models import profile
from .forms import createGameForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse,reverse_lazy
from django.contrib.auth.models import User

# Create your views here.
@login_required
def game(request,inviting,color):
    pending = Pending_Game.objects.get(inviting=inviting)
    time = pending.time
    increment = pending.increment
    return render(request, template_name='game/game.html', context={
        'inviting':inviting,
        'color':color,
        'white' : 'white',
        'black':'black',
        'time' : time*60,
        'increment' : increment,
        })

class LobbyView(LoginRequiredMixin,ListView):
    model = Pending_Game
    template_name = 'game/LobbyList.html'


'''class creategameView(LoginRequiredMixin,CreateView):
    model = Pending_Game
    template_name = 'game/creategameView.html'
    form_class = createGameForm
    success_url = reverse_lazy('game:lobby')    #aspetta dentro il wschannel aperto'''

class creategameView(LoginRequiredMixin,CreateView):
    model = Pending_Game
    template_name = 'game/creategameView.html'
    form_class = createGameForm
    success_url = reverse_lazy('game:lobby')

    def get_context_data(self, **kwargs):
        #Use this to add extra context.#
        context = super(creategameView, self).get_context_data(**kwargs)
        form = self.form_class(profileid=self.request.user)
        #form.instance.User = User.objects.get(id=self.request.user.id)
        #self.request.session['user_id'] = self.request.user.id

        return context

@login_required
def creategame(request):
    if request.method =='GET':
        try:
            invited =  request.GET['invited']
        except:
            invited = ''
        return render(request,template_name='game/creategameView.html',context = {'invited': invited})
    if request.method == 'POST':
        try:
            if int(request.POST['time']) <= 0 or int(request.POST['increment']) < 0:
                return Http404("Time and increment cannot be negative")
        except:
            return Http404("time and increment must be numeric values")
        p = Pending_Game()
        p.inviting = request.user.username
        p.time = request.POST['time']
        p.increment = request.POST['increment']
        p.color_inviting = request.POST['color_inviting']
        if len(request.POST['invited']) > 1:
            p.invited = request.GET['invited']
        p.save()
        return redirect(reverse('game:game',kwargs = {'inviting':p.inviting,'color':p.color_inviting}))

ChickenChess/game/templates/game/LobbyList.html
{% extends 'base.html' %}
{% block head %} <title>Games Lobby</title> {% endblock %} 
{% block content %}

<div class="container">
    <h2>Games Lobby</h2>

    <div>
    <a href="{% url 'game:creategame'%}">
    <button type="button" class="btn btn-dark" >Crea una nuova partita</button>
    </a>
    <button type="button" class="btn btn-dark" onClick="window.location.reload();">Refresh Lobby</button>
    </div>
    <table class="table table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>Inviting Player</th>
          <th>Invited player</th>
          <th>Time Mode</th>

        </tr>
      </thead>
      <tbody>
        {% for p in object_list %}
          {% if p.invited == request.user.username or p.invited == "" %}
        <tr>    
            <td>{{ p.inviting }} as {{p.color_inviting}}</td>
            <td>{{p.invited}}</td>
            <td>{{p.time}} + {{p.increment}}</td>
            <td>
              <a href="{% url 'game:game' inviting=p.inviting color=p.color_inviting %}" ><button type="button" class="btn btn-dark">Play</button></a>
            </td>
        <tr>
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>


{% endblock %}

ChickenChess/game/templates/game/creategameView.html
{% extends "base.html" %}

{% block head %}
<title>  Create a new Public Game </title>
{% load crispy_forms_tags %}
{% endblock head %}

{% block content %}
<center>
    <!--<h1>{{ view.form_class.description }}</h1>-->
    <!--{{form | crispy}}-->
    <!--{{form.as_p}}-->
    <h1>Crea una nuova partita</h1><br>
    <form method="POST">
        {% csrf_token %}
         <p>Select your color</p>
         <select name="color_inviting" class="select" required="" id="id_color_inviting">
             <option value="white">white</option>
             <option value="black">black</option>
         </select>
        <p>Select time format (minutes)</p>
        <input type="hidden" name="invited" id="id_invited" value="{{invited}}"> 
         <input type="number" min="1" name="time" class="numberinput" required="" id="id_time">
         <p>Select increment</p>
         <input type="number" min="0" name="increment" class="numberinput" required="" id="id_increment">
         <br><br>
         <input type="submit" class="btn btn-success" value="Crea Partita">
        
    
    </form>
</center>
{% endblock content %}

ChickenChess/game/templates/game/game.html
{% extends 'base.html' %}

{% block head %}

{% load static %}

{% endblock %}

{% block content %}

<style>
    body{
        background-image: url("{% static '/img/Home.jpg' %}"); background-size: cover;background-repeat: no-repeat;
    }
    .bg-image {
          opacity: 0.5;
        }
</style>

<script type="text/javascript">
    var img_path = "{% static '/img' %}";
    var time = {{time}};
    var increment = {{increment}};
    var othercolor = '';
    var username = '{{request.user.username}}';

    {% if color == white %}
        othercolor = 'black';
    {% else %}
        othercolor = 'white';
    {% endif %}


    {% if request.user.username == inviting %}

        var your_color = '{{color}}';
        

    {% else %}

        var your_color = othercolor

    {% endif %}
</script>

<!--Orologio Avversario-->
<div class="container p-3 my-3 bg-dark text-white" style="width: 300px;">
    <p id="Timer_opponent">{{time}}</p>
    <p id="opp_name"></p>
</div>

<!--Scacchiera-->
<div class="container">
    <center>
        <table id="chessboard" style='margin: 50px'>

        </table>
        <script src="{% static '/js/online_game.js' %}?t=12345"></script>
    </center>
</div>

<!--Orologio Tuo-->
<div class="container p-3 my-3 bg-dark text-white" style="width: 300px;">
    <p id="Timer_your">{{time}}</p>
    <p>{{request.user.username}}</p>
</div>


<!--Resign Button-->
<div class="container" id="panel" >
    <button type="button" class="btn btn-dark" id="resign" onclick="resign()">
        Resign
    </button>
</div>



{% endblock %}