ChickenChess/ChickenChess/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from .views import *
from .initdbs import *
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
import json

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$|^/$|^home/$', home, name='home'),
    path('partita', match, name='partita'),
    path('players/', include('players.urls')),
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("success/", success, name='success'),
    path('game/', include('game.urls'), name='game'),
    path('getmoves/',getmoves),
    path('makemove/',makemove),
    

    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

#erase_dbs()
#start_dbs()



ChickenChess/game/urls.py
from django.urls import path
from .views import *

app_name = 'game'

urlpatterns = [
 path("<str:inviting>/<str:color>/", game ,name="game"),
 path('lobby/', LobbyView.as_view() , name='lobby'),
 path('creategame/', creategame, name='creategame'),



]

ChickenChess/players/urls.py
from django.contrib import admin
from django.urls import path,re_path
from . import views

app_name = 'players'

urlpatterns = [
    path("", views.ListUserView.as_view(), name='listagiocatori' ),
    path("profiloutente/<pk>/", views.DetailProfileView.as_view(), name='profile'),
    
    
]

ChickenChess/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    {% block head %}
    {% endblock head %}
    {# {% load crispy_forms_tags %} #} 
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'players:listagiocatori' %}">Classifica</a>
          </li>

          {%if user.is_authenticated %}
          <li class="nav-item ">  
            <a class="nav-link" href="{% url 'game:lobby' %}">Lobby</a>
          </li>

          <li class="nav-item ">  
            <a class="nav-link" href={% url 'players:profile' pk=user.pk %}>Profilo</a>
          </li>
          
          <li class="nav-item ">  
            <a class="nav-link" href="{% url 'logout'%}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item ">  
            <a class="nav-link" href="{% url 'login'%}">Login</a>
          </li>

          <li class="nav-item ">  
            <a class="nav-link" href="{% url 'register' %}">Sign in</a>
          </li>
          {% endif %}
        </ul>
      </nav>

    {% block content %} {% endblock content %}
</body>

</html>

ChickenChess/templates/home.html
{% extends "base.html" %}

{% block head %}
<title>  ChickenChess Homepage  </title>
{% load static %}

<style
    <link rel="stylesheet" href='{% static "/css/style.css"%}'>
</style>
{% endblock head %}

{% block content %}


{% if user.is_authenticated and 'ok' in request.GET.login %}
<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Success!</strong> You succesfully logged in!
</div>
{% endif %}


<div class="jumbotron text-center">
    <h1>Homepage</h1>
    <p>ChickenChess</p> 
</div>

<center>
    <form action="{% url 'partita'%}" method="GET">
    <div class="form-check-inline">
        <label class="form-check-label">
          <input type="radio" class="form-check-input" name="color" value="white" checked>White
        </label>
      </div>
      <div class="form-check-inline">
        <label class="form-check-label">
          <input type="radio" class="form-check-input" name="color" value="black">Black
        </label>
      </div>
      <input type="submit" value="Play Stockfish">
    </form>

     <img src="{% static '/img/home.jpg' %}" class="rounded" alt="HomeIMG" width="1000" height="500">
 </center>

{% endblock content %}

ChickenChess/templates/stockfish.html
{% extends 'base.html' %}

{% block head %}

    {% load static %}
    <style
    <link rel="stylesheet" href='{% static "/css/style.css"%}'>
    </style> 

<title>  ChickenChess partita  </title>

{% endblock %}

{% block content %}

<style>
body{
    background-image: url("{% static '/img/Home.jpg' %}"); background-size: cover;background-repeat: no-repeat;
}
.bg-image {
      opacity: 0.5;
    }
</style>

{% for p in position.values %}
        <p>{{p}}</p>
{% endfor %}

<script type="text/javascript">
    var position = '{{position}}';
    var moves = '{{moves}}';
    var player_color = '{{player_color}}' 
    console.log(position);
    var path = "{% static '/img' %}";
</script>



<div class="container">
    <center>
        <table id="chessboard" style='margin: 50px'>

        </table>
        <script src="{% static '/js/offline_game.js' %}?t=123456"></script> <!--it has a dummy timestamp-->
    </center>
</div>


<div class="container" id="panel">
    <button type="button" class="btn btn-dark" id="resign" onclick="resign()">
        Resign
    </button>
</div> 

{% endblock %} 

ChickenChess/templates/success.html
<head>
    <title>Success</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  
  <body>
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1>Operation Successful</h1>
        <a href="{% url 'home'%}">Vai alla Home</a>
      </div>
    </div>
  </body>

ChickenChess/templates/user_create.html
{% extends "base.html" %}

{% block head %}
<title>  Sign in </title>
{% load crispy_forms_tags %}
{% endblock head %}

{% block content %}
<center>
    <form method="post"> {% csrf_token %}
    {{form | crispy}}
    
    <input type="submit" class="btn btn-success" value="Registrati ora!">
    
    </form>
</center>
{% endblock content %}